### ISSUE TITLE
【お酢健】コンテンツ一覧_リンク先修正依頼

### ISSUE THREAD

**Issue by sumida-tomomi** [oishi-kenko/katgut#13]
**概要**
7/30に改修した「お酢健」のコンテンツ一覧ページ、
リンク先が違うので、以下に修正をお願いします。

▼「減塩取り過ぎかも？！」記事
正）https://oishi-kenko.com/tieups/70

▼「出展のご報告」記事
正）https://oishi-kenko.com/tieups/69

テストUPで確認したはずなのに、お手数をお掛けします。
どうぞよろしくお願いします。

**Comment by tkatou84-ok** [comment]
https://github.com/oishi-kenko/kenko/pull/2798 で対応し、本番反映されました。

@sumida-tomomi ご確認いただけますでしょうか。
